Support pbs

diff --git a/workflow/yamls/openvscode/hsp.yaml b/workflow/yamls/openvscode/hsp.yaml
--- a/workflow/yamls/openvscode/hsp.yaml
+++ b/workflow/yamls/openvscode/hsp.yaml
@@ -108,12 +108,12 @@ jobs:
             # Wait before the next check
             sleep 5
           done
-          job_id=$(${sshcmd} cat ${resource_jobdir}/job.id)
-          if [ -z "${job_id}" ]; then
-            echo "Error: SLURM job ID is empty!" >&2
-            exit 1
-          fi
           if [[ "${{ inputs.pwrl_host.jobschedulertype }}" == "SLURM" ]]; then
+            job_id=$(${sshcmd} cat ${resource_jobdir}/job.id)
+            if [ -z "${job_id}" ]; then
+              echo "Error: SLURM job ID is empty!" >&2
+              exit 1
+            fi
             target_hostname=$(${sshcmd} squeue -j "${job_id}" --noheader --format="%N")
           fi
           echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
