Update jupyterlab to use the session runner subworkflow

diff --git a/workflow/yamls/activate.yaml b/workflow/yamls/activate.yaml
--- a/workflow/yamls/activate.yaml
+++ b/workflow/yamls/activate.yaml
@@ -1,88 +1,86 @@
 permissions:
   - '*'
-
 jobs:
   preprocessing:
-      working-directory: ${{ inputs.service.rundir }}
-      ssh:
-        remoteHost: ${{ inputs.resource.ip }}
-      steps:
-        - name: Controller Preprocessing
-          run: |
-            set -x
-            echo "slurm_is_disabled${{ inputs.slurm.is_disabled }}"
-            echo "pbs_is_disabled${{ inputs.pbs.is_disabled }}"
-            # This script prepares the target host and always runs in the controller node
-            cp ${{ inputs.service.inputs_sh }} ${{ inputs.service.rundir }}/controller-preprocessing-${PW_JOB_ID}.sh
-            cat ${{ inputs.service.controller_script }} >> ${{ inputs.service.rundir }}/controller-preprocessing-${PW_JOB_ID}.sh
-            bash ${{ inputs.service.rundir }}/controller-preprocessing-${PW_JOB_ID}.sh
-        - name: Create Service Script
-          run: |
-            # This script starts the service
-            cp ${{ inputs.service.inputs_sh }} ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
-            # TRANSITION CODE
-            echo resource_jobdir=${PW_PARENT_JOB_DIR} >> ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
-            # basepath
-            PW_JOB_NUMBER_STRIPPED=$(printf '%d' "$PW_JOB_NUMBER")
-            session_name="${PW_WORKFLOW_NAME}_${PW_JOB_NUMBER_STRIPPED}_session_runner_step_0_session"
-            basepath=/me/session/${PW_USER}/${session_name}
-            slug="vnc.html?resize=remote&autoconnect=true&show_dot=true&path=websockify&password=${password}&host=${PW_PLATFORM_HOST}${basepath}/&dt=0"
-            echo "slug=${slug}"  | tee -a $OUTPUTS
-            # Write code common to all services
-            cat <<'EOF' >> ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
+    working-directory: ${{ inputs.service.rundir }}
+    ssh:
+      remoteHost: ${{ inputs.resource.ip }}
+    steps:
+      - name: Controller Preprocessing
+        run: |
+          set -x
+          echo "slurm_is_disabled${{ inputs.slurm.is_disabled }}"
+          echo "pbs_is_disabled${{ inputs.pbs.is_disabled }}"
+          # This script prepares the target host and always runs in the controller node
+          cp ${{ inputs.service.inputs_sh }} ${{ inputs.service.rundir }}/controller-preprocessing-${PW_JOB_ID}.sh
+          cat ${{ inputs.service.controller_script }} >> ${{ inputs.service.rundir }}/controller-preprocessing-${PW_JOB_ID}.sh
+          bash ${{ inputs.service.rundir }}/controller-preprocessing-${PW_JOB_ID}.sh
+      - name: Create Service Script
+        run: |
+          # This script starts the service
+          cp ${{ inputs.service.inputs_sh }} ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
+          # TRANSITION CODE
+          echo resource_jobdir=${PW_PARENT_JOB_DIR} >> ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
+          # basepath
+          PW_JOB_NUMBER_STRIPPED=$(printf '%d' "$PW_JOB_NUMBER")
+          session_name="${PW_WORKFLOW_NAME}_${PW_JOB_NUMBER_STRIPPED}_session_runner_step_0_session"
+          basepath=/me/session/${PW_USER}/${session_name}
+          slug="vnc.html?resize=remote&autoconnect=true&show_dot=true&path=websockify&password=${password}&host=${PW_PLATFORM_HOST}${basepath}/&dt=0"
+          echo "slug=${slug}"  | tee -a $OUTPUTS
+          # Write code common to all services
+          cat <<'EOF' >> ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
 
-            if [ -z "${service_port}" ]; then
-              service_port=$(pw agent open-port)
-            fi
+          if [ -z "${service_port}" ]; then
+            service_port=$(pw agent open-port)
+          fi
 
-            if [ -z "${service_port}" ]; then
-              echo "$(date) ERROR: No service port found"
-              exit 1            
-            fi
-            echo ${service_port} > SESSION_PORT
-            hostname > HOSTNAME
+          if [ -z "${service_port}" ]; then
+            echo "$(date) ERROR: No service port found"
+            exit 1            
+          fi
+          echo ${service_port} > SESSION_PORT
+          hostname > HOSTNAME
 
-            cleanup() {
-                echo "$(date) Cleaning up..."
-                kill -- -$$
-            }
+          cleanup() {
+              echo "$(date) Cleaning up..."
+              kill -- -$$
+          }
 
-            trap cleanup EXIT INT TERM
+          trap cleanup EXIT INT TERM
 
-            echo
-            echo
-            echo "$(date) STARTING SERVICE"
-            echo
-            touch job.started
-            EOF
-            cat ${{ inputs.service.start_service_script }} >> ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
-            # TRANSITION CODE
-            sed -i 's/findAvailablePort/pw agent open-port/' ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
-
+          echo
+          echo
+          echo "$(date) STARTING SERVICE"
+          echo
+          touch job.started
+          EOF
+          cat ${{ inputs.service.start_service_script }} >> ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
+          # TRANSITION CODE
+          sed -i 's/findAvailablePort/pw agent open-port/' ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
   session_runner:
     working-directory: ${{ inputs.service.rundir }}
     needs:
       - preprocessing
     ssh:
-        remoteHost: ${{ inputs.resource.ip }}
+      remoteHost: ${{ inputs.resource.ip }}
     steps:
-      - uses: marketplace/script_submitter/v3.6
+      - uses: marketplace/script_submitter/v1234
         early-cancel: any-job-failed
         with:
           resource: ${{ inputs.resource }}
           shebang: '#!/bin/bash'
           rundir: ${{ inputs.service.rundir }}
           use_existing_script: true
-          script_path: "${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh"
-          scheduler: ${{ inputs.cluster.scheduler }}
+          script_path: ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
+          scheduler: ${{ inputs.scheduler }}
           slurm:
-            is_disabled: ${{ inputs.cluster.slurm.is_disabled }}
-            partition: ${{ inputs.cluster.slurm.partition }}
-            scheduler_directives: ${{ inputs.cluster.slurm.scheduler_directives }}
-            time: ${{ inputs.cluster.slurm.time }}
+            is_disabled: ${{ inputs.slurm.is_disabled }}
+            partition: ${{ inputs.slurm.partition }}
+            scheduler_directives: ${{ inputs.slurm.scheduler_directives }}
+            time: ${{ inputs.slurm.time }}
           pbs:
-            is_disabled: ${{ inputs.cluster.pbs.is_disabled }}
-            scheduler_directives: ${{ inputs.cluster.pbs.scheduler_directives }}
+            is_disabled: ${{ inputs.pbs.is_disabled }}
+            scheduler_directives: ${{ inputs.pbs.scheduler_directives }}
       - name: Notify job ended
         early-cancel: any-job-failed
         run: |
@@ -90,8 +88,6 @@ jobs:
           pwd
           touch job.ended
           ls -lat job.ended
-
-
   wait_for_job_start:
     working-directory: ${{ inputs.service.rundir }}
     needs:
@@ -122,7 +118,6 @@ jobs:
             echo "$(date) Failed to get target hostname"
             exit 1
           fi
-
   cleanup:
     working-directory: ${{ inputs.service.rundir }}
     if: ${{ always }}
@@ -133,7 +128,7 @@ jobs:
       remoteHost: ${{ inputs.resource.ip }}
     steps:
       - name: Controller cleanup
-        if: ${{ inputs.cluster.slurm.is_disabled && inputs.cluster.pbs.is_disabled }}
+        if: ${{ inputs.slurm.is_disabled && inputs.pbs.is_disabled }}
         run: echo "$(date) Cleaning up..."
         cleanup: |
           set -x
@@ -141,7 +136,7 @@ jobs:
             bash cancel.sh
           fi
       - name: Compute cleanup
-        if: ${{ (inputs.cluster.slurm.is_disabled == false || inputs.cluster.pbs.is_disabled == false) }}
+        if: ${{ (inputs.slurm.is_disabled == false || inputs.pbs.is_disabled == false) }}
         run: echo "Cleaning up..."
         cleanup: |
           set -x
@@ -154,7 +149,6 @@ jobs:
           if [ -f cancel.sh ]; then
             ${sshcmd} 'bash -s' < ${PWD}/cancel.sh
           fi
-
   create_session:
     working-directory: ${{ inputs.service.rundir }}
     needs:
@@ -208,14 +202,11 @@ jobs:
       - name: Update Session
         uses: parallelworks/update-session
         with:
-          target: '${{ inputs.resource.id }}'
-          name: '${{ inputs.session }}'
-          slug: '${{ inputs.service.slug }}'
-          remoteHost: '${{ needs.wait_for_job_start.outputs.HOSTNAME }}'
-          remotePort: '${{ needs.create_session.outputs.SESSION_PORT }}'
-
-
-
+          target: ${{ inputs.resource.id }}
+          name: ${{ inputs.session }}
+          slug: ${{ inputs.service.slug }}
+          remoteHost: ${{ needs.wait_for_job_start.outputs.HOSTNAME }}
+          remotePort: ${{ needs.create_session.outputs.SESSION_PORT }}
 'on':
   execute:
     inputs:
@@ -227,61 +218,57 @@ jobs:
         label: Service host
         include-workspace: false
         tooltip: Resource to host the service
-      cluster:
+      scheduler:
+        type: boolean
+        default: false
+        label: Schedule Job?
         hidden: ${{ inputs.resource.schedulerType == '' }}
-        ignore: ${{ inputs.resource.schedulerType == ''  }}
+        ignore: ${{ .hidden }}
+        tooltip: |
+          Yes → Job is submitted to the scheduler using sbatch, qsub, etc
+          No  → Job is executed in the controller or login node instead
+      slurm:
         type: group
-        label: Compute Cluster Settings
+        label: SLURM Directives
+        hidden: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.scheduler == false }}
+        ignore: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.scheduler == false }}
         items:
-          scheduler:
+          is_disabled:
             type: boolean
-            default: false
-            label: Schedule Job?
+            hidden: true
+            default: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.scheduler == false }}
+            label: Is SLURM disabled?
+          partition:
+            type: slurm-partitions
+            label: SLURM partition
+            optional: true
+            resource: ${{ inputs.resource }}
+            tooltip: Select a partition from the drop down menu.
+          time:
+            label: Walltime
+            type: string
+            default: '01:00:00'
+            tooltip: '--time= SLURM directive to set the maximum wall-clock time limit for the job'
+          scheduler_directives:
+            type: editor
+            optional: true
             tooltip: |
-              Yes → Job is submitted to the scheduler using sbatch, qsub, etc
-              No  → Job is executed in the controller or login node instead
-          slurm:
-            type: group
-            label: SLURM Directives
-            hidden: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
-            ignore: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
-            items:
-              is_disabled:
-                type: boolean
-                hidden: true
-                default: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
-                label: Is SLURM disabled?
-              partition:
-                type: slurm-partitions
-                label: SLURM partition
-                optional: true
-                resource: ${{ inputs.resource }}
-                tooltip: Select a partition from the drop down menu.
-              time:
-                label: Walltime
-                type: string
-                default: '01:00:00'
-                tooltip: '--time= SLURM directive to set the maximum wall-clock time limit for the job'
-              scheduler_directives:
-                type: editor
-                optional: true
-                tooltip: |
-                  Type in additional scheduler directives. 
-          pbs:
-            type: group
-            label: PBS Directives
-            hidden: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
-            ignore: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
-            items:
-              is_disabled:
-                type: boolean
-                hidden: true
-                default: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
-                label: Is PBS disabled?
-              scheduler_directives:
-                label: Scheduler Directives
-                type: editor
-                tooltip: Type the PBS scheduler directives
+              Type in additional scheduler directives. 
+      pbs:
+        type: group
+        label: PBS Directives
+        hidden: ${{ inputs.resource.schedulerType != 'pbs' || inputs.scheduler == false }}
+        ignore: ${{ inputs.resource.schedulerType != 'pbs' || inputs.scheduler == false }}
+        items:
+          is_disabled:
+            type: boolean
+            hidden: true
+            default: ${{ inputs.resource.schedulerType != 'pbs' || inputs.scheduler == false }}
+            label: Is PBS disabled?
+          scheduler_directives:
+            label: Scheduler Directives
+            type: editor
+            tooltip: Type the PBS scheduler directives
       service:
         type: group
         label: Service
