Add PBS support

diff --git a/workflow/yamls/vncserver/hsp.yaml b/workflow/yamls/vncserver/hsp.yaml
--- a/workflow/yamls/vncserver/hsp.yaml
+++ b/workflow/yamls/vncserver/hsp.yaml
@@ -86,7 +86,7 @@ jobs:
         run: |
           target_hostname=$(${sshcmd} hostname)
           echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
-      - name: Get Compute Hostname
+      - name: Get SLURM Compute Hostname
         early-cancel: any-job-failed
         if: ${{ 'SLURM' == inputs.pwrl_host.jobschedulertype }}
         env:
@@ -117,7 +117,37 @@ jobs:
           fi
           target_hostname=$(${sshcmd} squeue -j "${job_id}" --noheader --format="%N")
           echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
+      - name: Get PBS Compute Hostname
+        early-cancel: any-job-failed
+        if: ${{ 'PBS' == inputs.pwrl_host.jobschedulertype }}
+        env:
+          sshcmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ inputs.pwrl_host.resource.ip }}
+        run: |
+          source utils/load-env.sh
+          source resources/host/inputs.sh
+          while true; do
+            failIfError
+            echo "Waiting for target hostname..."
 
+            # Check if the service.port file exists and read its contents
+            target_hostname=$(${sshcmd} "if [ -f ${resource_jobdir}/target.hostname ]; then cat ${resource_jobdir}/target.hostname; fi")
+
+            # Exit the loop if file was found and read
+            if [ -n "${target_hostname}" ]; then
+              echo "Target's hostname found: ${target_hostname}"
+              break
+            fi
+
+            # Wait before the next check
+            sleep 5
+          done
+          job_id=$(${sshcmd} cat ${resource_jobdir}/job.id)
+          if [ -z "${job_id}" ]; then
+            echo "Error: PBS job ID is empty!" >&2
+            exit 1
+          fi
+          target_hostname=$(${sshcmd} qstat -f "${jobid}" | awk -F= '/exec_host/ {print $2}' | cut -d'+' -f1 | cut -d'/' -f1)
+          echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
       - name: Get Remote Port
         early-cancel: any-job-failed
         env:
