Add annotations

diff --git a/workflow/session_runner/v1.4/general.yaml b/workflow/session_runner/v1.4/general.yaml
--- a/workflow/session_runner/v1.4/general.yaml
+++ b/workflow/session_runner/v1.4/general.yaml
@@ -28,15 +28,15 @@ jobs:
           fi
 
           if [ -z "${service_port}" ]; then
-            echo "$(date) ERROR: No service port found"
-            exit 1            
+            echo "::error title=Error::No service port found"
+            exit 1
           fi
           echo ${service_port} > SESSION_PORT
           hostname > HOSTNAME
 
           cleanup() {
               trap - EXIT INT TERM HUP QUIT USR1 USR2 PIPE
-              echo "$(date) Cleaning up..."
+              echo "::notice::Cleaning up..."
               mv cancel.sh cancel.sh.submitted
               echo "echo Cleanup script was already executed" > cancel.sh
               bash cancel.sh.submitted
@@ -45,10 +45,7 @@ jobs:
 
           trap cleanup EXIT INT TERM HUP QUIT USR1 USR2 PIPE
 
-          echo
-          echo
-          echo "$(date) STARTING SERVICE"
-          echo
+          echo "::notice::Starting service"
           touch job.started
           EOF
           cat ${{ inputs.service.start_service_script }} >> ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
@@ -102,10 +99,10 @@ jobs:
           set -x
           while [ ! -f job.started ]; do
             if [ -f job.ended ]; then
-              echo "$(date) Job ended before it started. Exiting."
+              echo "::error title=Error::Job ended before it started. Exiting."
               exit 1
             fi
-            echo "$(date) Waiting for job to start..."
+            echo "::debug::Waiting for job to start..."
             sleep 5
           done
       - name: Get Hostname
@@ -116,7 +113,7 @@ jobs:
           echo "HOSTNAME=${HOSTNAME}" | tee -a $OUTPUTS
 
           if [ -z "${HOSTNAME}" ]; then
-            echo "$(date) Failed to get target hostname"
+            echo "::error title=Error::Failed to get target hostname"
             exit 1
           fi
 
@@ -137,7 +134,7 @@ jobs:
           echo "SESSION_PORT=${SESSION_PORT}" | tee -a $OUTPUTS
 
           if [ -z "${SESSION_PORT}" ]; then
-            echo "$(date) Failed to get target session's port"
+            echo "::error title=Error::Failed to get target session's port"
             exit 1
           fi
       - name: Wait for Server To Start
@@ -157,16 +154,16 @@ jobs:
           # Main loop
           attempt=1
           while true; do
-              echo "$(date) Attempt $attempt: Checking if server is listening on ${remote_host}:${remote_port}..."
-              
+              echo "::debug::Attempt $attempt: Checking if server is listening on ${remote_host}:${remote_port}..."
+
               if check_server; then
-                  echo "$(date) Success: Server is listening on ${remote_host}:${remote_port}!"
+                  echo "::notice::Server is listening on ${remote_host}:${remote_port}!"
                   exit 0
               elif [ -f job.ended ]; then
-                  echo "$(date) Job was completed. Exiting... "
+                  echo "::notice::Job was completed. Exiting..."
                   exit 0
               else
-                  echo "$(date) Server not responding. Retrying in ${RETRY_INTERVAL} seconds..."
+                  echo "::debug::Server not responding. Retrying in ${RETRY_INTERVAL} seconds..."
                   sleep "$RETRY_INTERVAL"
                   ((attempt++))
               fi
@@ -179,6 +176,9 @@ jobs:
           slug: ${{ inputs.service.slug }}
           remoteHost: ${{ needs.wait_for_job_start.outputs.HOSTNAME }}
           remotePort: ${{ needs.create_session.outputs.SESSION_PORT }}
+      - name: Session Ready
+        run: |
+          echo "::notice title=Ready::Session is ready"
 'on':
   execute:
     inputs:
