Use PROJECTS_HOME instead of workdir

diff --git a/workflow/session_runner/v1.4/hsp.yaml b/workflow/session_runner/v1.4/hsp.yaml
--- a/workflow/session_runner/v1.4/hsp.yaml
+++ b/workflow/session_runner/v1.4/hsp.yaml
@@ -15,23 +15,23 @@ jobs:
           # This script prepares the target host and always runs in the controller node
           if [ -n "${service_parent_install_dir}" ]; then
             echo "::notice title=Install Directory::Using provided service_parent_install_dir: ${service_parent_install_dir}"
-          elif [ -z "${WORKDIR}" ]; then
-            echo "::error title=Install Directory::WORKDIR is empty"
+          elif [ -z "${PROJECTS_HOME}" ]; then
+            echo "::error title=Install Directory::PROJECTS_HOME is empty"
             exit 1
           else
-            hsp_workdir="${WORKDIR/$USER/avidalto}/hsp"
-            if [ ! -d "${hsp_workdir}" ]; then
-              if ! mkdir -p "${hsp_workdir}"; then
-                echo "::error title=Install Directory::Failed to create ${hsp_workdir} - permission denied"
+            hsp_install_dir="${PROJECTS_HOME}/hsp"
+            if [ ! -d "${hsp_install_dir}" ]; then
+              if ! mkdir -p "${hsp_install_dir}"; then
+                echo "::error title=Install Directory::Failed to create ${hsp_install_dir} - permission denied"
                 exit 1
               fi
-              if ! chmod g+rwx,o+rx "${hsp_workdir}"; then
-                echo "::error title=Install Directory::Failed to set permissions on ${hsp_workdir} - permission denied"
+              if ! chmod g+rwx,o+rx "${hsp_install_dir}"; then
+                echo "::error title=Install Directory::Failed to set permissions on ${hsp_install_dir} - permission denied"
                 exit 1
               fi
             fi
-            echo "::notice title=Install Directory::Using WORKDIR: ${hsp_workdir}"
-            echo "service_parent_install_dir=${hsp_workdir}" >> inputs.sh
+            echo "::notice title=Install Directory::Using Install Directory: ${hsp_install_dir}"
+            echo "service_parent_install_dir=${hsp_install_dir}" >> inputs.sh
           fi
 
       - name: Controller Preprocessing
