Step fails if any job fails

diff --git a/workflow/yamls/jupyterlab-host/emed.yaml b/workflow/yamls/jupyterlab-host/emed.yaml
--- a/workflow/yamls/jupyterlab-host/emed.yaml
+++ b/workflow/yamls/jupyterlab-host/emed.yaml
@@ -81,11 +81,10 @@ jobs:
         env:
           sshcmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ inputs.pwrl_host.resource.ip }}
         run: |
-          source resources/host/inputs.sh
           source utils/load-env.sh
+          source resources/host/inputs.sh
           while true; do
             failIfError
-            
             echo "Waiting for target hostname..."
 
             # Check if the service.port file exists and read its contents
@@ -100,6 +99,11 @@ jobs:
             # Wait before the next check
             sleep 5
           done
+          job_id=$(${sshcmd} cat ${resource_jobdir}/job.id)
+          if [ -z "${job_id}" ]; then
+            echo "Error: SLURM job ID is empty!" >&2
+            exit 1
+          fi
           target_hostname=$(${sshcmd} squeue -j "${job_id}" --noheader --format="%N")
           echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
 
