Add juice

diff --git a/workflow/yamls/jupyterlab-host/general_k8s.yaml b/workflow/yamls/jupyterlab-host/general_k8s.yaml
--- a/workflow/yamls/jupyterlab-host/general_k8s.yaml
+++ b/workflow/yamls/jupyterlab-host/general_k8s.yaml
@@ -188,56 +188,56 @@ jobs:
         if: ${{ inputs.targetType === 'kubernetes-cluster' }}
         run: pw kube auth ${{ inputs.k8s.cluster }}
   prepare_k8s_pvc:
-    needs:
-      - auth_k8s
-    steps:
-      - name: Creating New PVC YAML
-        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-        run: |
-          if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
-            pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
-          else
-            job_number=$(pwd | rev | cut -d "/" -f1 | rev)
-            workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
-            pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
-          fi
-          pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
-          if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
-            default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
-            if [ $? -ne 0 ]; then
-              echo "WARNING: Could not obtain default storageClass with command:"
-              echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
-              echo "         You might need to provide a storage class input"
-            elif [ -z "${default_class}" ]; then
-              echo "ERROR: No default storage class found. You must specify one explicitly."
-              exit 1
+      needs:
+        - auth_k8s
+      steps:
+        - name: Creating New PVC YAML
+          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+          run: |
+            if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
+              pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
+            else
+              job_number=$(pwd | rev | cut -d "/" -f1 | rev)
+              workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
+              pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
             fi
-          else
-            storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
-          fi
-          echo "${pvc_name}" > pvc_name
-          cat <<EOF > pvc.yaml
-          apiVersion: v1
-          kind: PersistentVolumeClaim
-          metadata:
-            name: ${pvc_name}
-            namespace: ${{ inputs.k8s.namespace }}
-          spec:
-            accessModes:
-              - ReadWriteOnce
-            resources:
-              requests:
-                storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
-            ${storageClassName} 
-          EOF
-          cat pvc.yaml
-      - name: Dry Run PVC
-        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-        run: |
-          echo "Performing dry run..."
-          kubectl apply -f pvc.yaml --dry-run=client
-      - name: Dummy
-        run: echo Dummy
+            pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
+            if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
+              default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
+              if [ $? -ne 0 ]; then
+                echo "WARNING: Could not obtain default storageClass with command:"
+                echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
+                echo "         You might need to provide a storage class input"
+              elif [ -z "${default_class}" ]; then
+                echo "ERROR: No default storage class found. You must specify one explicitly."
+                exit 1
+              fi
+            else
+              storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
+            fi
+            echo "${pvc_name}" > pvc_name
+            cat <<EOF > pvc.yaml
+            apiVersion: v1
+            kind: PersistentVolumeClaim
+            metadata:
+              name: ${pvc_name}
+              namespace: ${{ inputs.k8s.namespace }}
+            spec:
+              accessModes:
+                - ReadWriteOnce
+              resources:
+                requests:
+                  storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
+              ${storageClassName} 
+            EOF
+            cat pvc.yaml
+        - name: Dry Run PVC
+          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+          run: |
+            echo "Performing dry run..."
+            kubectl apply -f pvc.yaml --dry-run=client
+        - name: Dummy
+          run: echo Dummy
   prepare_k8s_deployment:
     needs:
       - prepare_k8s_pvc
@@ -468,6 +468,7 @@ jobs:
             namespace: ${{ inputs.k8s.namespace }}
             resourceType: services
             resourceName: ${{ needs.create_k8s_session.outputs.service_name }}
+
 'on':
   execute:
     inputs:
