Add pbs support

diff --git a/workflow/yamls/jupyterlab-host/general_k8s.yaml b/workflow/yamls/jupyterlab-host/general_k8s.yaml
--- a/workflow/yamls/jupyterlab-host/general_k8s.yaml
+++ b/workflow/yamls/jupyterlab-host/general_k8s.yaml
@@ -94,12 +94,14 @@ jobs:
           echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
       - name: Get Compute Hostname
         early-cancel: any-job-failed
-        if: ${{ 'SLURM' == inputs.pwrl_host.jobschedulertype && inputs.targetType == 'compute-cluster' }}
+        if: ${{ 'SLURM' == inputs.pwrl_host.jobschedulertype || 'PBS' == inputs.pwrl_host.jobschedulertype }}
         env:
           sshcmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ inputs.pwrl_host.resource.ip }}
         run: |
+          source utils/load-env.sh
           source resources/host/inputs.sh
           while true; do
+            failIfError
             echo "Waiting for target hostname..."
 
             # Check if the service.port file exists and read its contents
@@ -114,13 +116,16 @@ jobs:
             # Wait before the next check
             sleep 5
           done
-          job_id=$(${sshcmd} cat ${resource_jobdir}/job.id)
-          if [ -z "${job_id}" ]; then
-            echo "Error: SLURM job ID is empty!" >&2
-            exit 1
+          if [[ "${{ inputs.pwrl_host.jobschedulertype }}" == "SLURM" ]]; then
+            job_id=$(${sshcmd} cat ${resource_jobdir}/job.id)
+            if [ -z "${job_id}" ]; then
+              echo "Error: SLURM job ID is empty!" >&2
+              exit 1
+            fi
+            target_hostname=$(${sshcmd} squeue -j "${job_id}" --noheader --format="%N")
           fi
-          target_hostname=$(${sshcmd} squeue -j "${job_id}" --noheader --format="%N")
           echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
+
       - name: Get Remote Port
         early-cancel: any-job-failed
         if: ${{ inputs.targetType == 'compute-cluster' }}
