Support juice

diff --git a/workflow/yamls/jupyterlab-host/general_k8s.yaml b/workflow/yamls/jupyterlab-host/general_k8s.yaml
--- a/workflow/yamls/jupyterlab-host/general_k8s.yaml
+++ b/workflow/yamls/jupyterlab-host/general_k8s.yaml
@@ -18,6 +18,9 @@ jobs:
         run: |
           set -e
           echo "export basepath=/me/session/${PW_USER}/${{ sessions.session }}"  >> resources/host/inputs.sh
+          if ! [ -z ${{ org.JUICE_TOKEN }} ]; then
+            echo "export JUICE_TOKEN=${{ org.JUICE_TOKEN }}"
+          fi
           ./utils/steps-v3/preprocessing/process_inputs_sh.sh 
       - name: Transfer Files to Controller
         if: ${{ inputs.targetType === 'compute-cluster' }}
@@ -128,8 +131,6 @@ jobs:
             sleep 5
           done
           echo "remote_port=${remote_port}"  | tee -a $OUTPUTS
-
-
       - name: Waiting for Server to Start
         if: ${{ inputs.targetType === 'compute-cluster' }}
         env:
@@ -187,56 +188,56 @@ jobs:
         if: ${{ inputs.targetType === 'kubernetes-cluster' }}
         run: pw kube auth ${{ inputs.k8s.cluster }}
   prepare_k8s_pvc:
-      needs:
-        - auth_k8s
-      steps:
-        - name: Creating New PVC YAML
-          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-          run: |
-            if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
-              pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
-            else
-              job_number=$(pwd | rev | cut -d "/" -f1 | rev)
-              workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
-              pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+    needs:
+      - auth_k8s
+    steps:
+      - name: Creating New PVC YAML
+        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+        run: |
+          if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
+            pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
+          else
+            job_number=$(pwd | rev | cut -d "/" -f1 | rev)
+            workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
+            pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+          fi
+          pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
+          if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
+            default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
+            if [ $? -ne 0 ]; then
+              echo "WARNING: Could not obtain default storageClass with command:"
+              echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
+              echo "         You might need to provide a storage class input"
+            elif [ -z "${default_class}" ]; then
+              echo "ERROR: No default storage class found. You must specify one explicitly."
+              exit 1
             fi
-            pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
-            if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
-              default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
-              if [ $? -ne 0 ]; then
-                echo "WARNING: Could not obtain default storageClass with command:"
-                echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
-                echo "         You might need to provide a storage class input"
-              elif [ -z "${default_class}" ]; then
-                echo "ERROR: No default storage class found. You must specify one explicitly."
-                exit 1
-              fi
-            else
-              storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
-            fi
-            echo "${pvc_name}" > pvc_name
-            cat <<EOF > pvc.yaml
-            apiVersion: v1
-            kind: PersistentVolumeClaim
-            metadata:
-              name: ${pvc_name}
-              namespace: ${{ inputs.k8s.namespace }}
-            spec:
-              accessModes:
-                - ReadWriteOnce
-              resources:
-                requests:
-                  storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
-              ${storageClassName} 
-            EOF
-            cat pvc.yaml
-        - name: Dry Run PVC
-          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-          run: |
-            echo "Performing dry run..."
-            kubectl apply -f pvc.yaml --dry-run=client
-        - name: Dummy
-          run: echo Dummy
+          else
+            storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
+          fi
+          echo "${pvc_name}" > pvc_name
+          cat <<EOF > pvc.yaml
+          apiVersion: v1
+          kind: PersistentVolumeClaim
+          metadata:
+            name: ${pvc_name}
+            namespace: ${{ inputs.k8s.namespace }}
+          spec:
+            accessModes:
+              - ReadWriteOnce
+            resources:
+              requests:
+                storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
+            ${storageClassName} 
+          EOF
+          cat pvc.yaml
+      - name: Dry Run PVC
+        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+        run: |
+          echo "Performing dry run..."
+          kubectl apply -f pvc.yaml --dry-run=client
+      - name: Dummy
+        run: echo Dummy
   prepare_k8s_deployment:
     needs:
       - prepare_k8s_pvc
@@ -789,3 +790,20 @@ jobs:
             label: Use Token Authentication?
             type: boolean
             tooltip: Enable token-based authentication. Some containers may not support it.
+      juice:
+        type: group
+        label: Juice Settings
+        collapsed: true
+        items:
+          use_juice:
+            label: Enable Juice?
+            type: boolean
+            default: false
+            tooltip: Enable Juice to access and share remote GPUs over a network for your workload.
+          cmd_args:
+            label: Juice Run Command Arguments
+            type: string
+            hidden: ${{ inputs.juice.use_juice == false }}
+            ignore: ${{ .hidden }}
+            optional: true
+            tooltip: Optional arguments for the Juice run command to customize workload execution, e.g., "--pool-ids <pool_id>" to specify resource pools.
