Creating hsp version

diff --git a/workflow/yamls/jupyterlab-host/hsp.yaml b/workflow/yamls/jupyterlab-host/hsp.yaml
--- a/workflow/yamls/jupyterlab-host/hsp.yaml
+++ b/workflow/yamls/jupyterlab-host/hsp.yaml
@@ -1,25 +1,194 @@
+permissions:
+  - '*'
+sessions:
+  session:
+    useTLS: false
+    redirect: true
+
 jobs:
-  main:
+  preprocessing:
     steps:
-      - name: Preprocessing
-        run: ./utils/steps/preprocessing.sh
       - name: Validating Target Resource
-        run: ./utils/steps/input_form_resource_wrapper.sh
+        early-cancel: any-job-failed
+        run: ./utils/steps-v3/preprocessing/input_form_resource_wrapper.sh ${{ inputs.pwrl_host.resource.ip }}
       - name: Process Inputs
-        run: ./utils/steps/process_inputs_sh.sh
+        early-cancel: any-job-failed
+        run: |
+          set -e
+          echo "export basepath=/me/session/${PW_USER}/${{ sessions.session }}"  >> resources/host/inputs.sh
+          ./utils/steps-v3/preprocessing/process_inputs_sh.sh
+      - name: Transfer Files to Controller
+        early-cancel: any-job-failed
+        run: ./utils/steps-v3/preprocessing/transfer_files_to_controller.sh
       - name: Controller Preprocessing
-        run: ./utils/steps/controller_preprocessing.sh
-      - name: Prepare Service JSON
-        run: ./utils/steps/prepare_service_json.sh
+        early-cancel: any-job-failed
+        run: ./utils/steps-v3/preprocessing/controller_preprocessing.sh
       - name: Initialize Cancel Script
-        run: ./utils/steps/initialize_cancel_script.sh
-      - name: Create Session Script
-        run: ./utils/steps/create_session_script.sh
-      - name: Launch Job and Wait
-        run: ./utils/steps/launch_job_and_wait.sh
-        cleanup: ./kill.sh
+        early-cancel: any-job-failed
+        run: ./utils/steps-v3/preprocessing/initialize_cancel_script.sh
+
+  controller_job:
+    needs:
+      - preprocessing
+    steps:
+      - name: Create Controller Session Script
+        early-cancel: any-job-failed
+        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype }}
+        run: ./utils/steps-v3/controller/create_session_script.sh
+      - name: Launch and Monitor Controller Job
+        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype }}
+        run: ./utils/steps-v3/controller/launch_and_monitor_job.sh
+        cleanup: |
+          if [[ "${{ inputs.pwrl_host.jobschedulertype }}" == "CONTROLLER" ]]; then
+            ./kill.sh
+          fi
       - name: Clean and Exit
-        run: ./utils/steps/clean_and_exit.sh
+        early-cancel: any-job-failed
+        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype }}
+        run: ./utils/steps-v3/clean_and_exit.sh
+
+  compute_job:
+    needs:
+      - preprocessing
+    steps:
+      - name: Create Compute Session Script
+        early-cancel: any-job-failed
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype }}
+        run: ./utils/steps-v3/compute/create_session_script.sh
+      - name: Launch and Monitor Compute Job
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype }}
+        run: ./utils/steps-v3/compute/launch_and_monitor_job.sh
+        cleanup: |
+          if [[ "${{ inputs.pwrl_host.jobschedulertype }}" != "CONTROLLER" ]]; then
+            ./kill.sh
+          fi
+      - name: Clean and Exit
+        early-cancel: any-job-failed
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype }}
+        run: ./utils/steps-v3/clean_and_exit.sh
+
+  create_session:
+    needs:
+      - preprocessing
+    steps:
+      - name: Set Session Name
+        early-cancel: any-job-failed
+        run: |
+          session_name=$(pwd | rev | cut -d'/' -f1-2 | tr '/' '-' | rev)
+          echo "session_name=${session_name}" | tee -a $OUTPUTS
+      - name: Get Controller Hostname
+        early-cancel: any-job-failed
+        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype }}
+        env:
+          sshcmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ inputs.pwrl_host.resource.ip }}
+        run: |
+          target_hostname=$(${sshcmd} hostname)
+          echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
+      - name: Get Compute Hostname
+        early-cancel: any-job-failed
+        if: ${{ 'SLURM' == inputs.pwrl_host.jobschedulertype }}
+        env:
+          sshcmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ inputs.pwrl_host.resource.ip }}
+        run: |
+          source utils/load-env.sh
+          source resources/host/inputs.sh
+          while true; do
+            failIfError
+            echo "Waiting for target hostname..."
+
+            # Check if the service.port file exists and read its contents
+            target_hostname=$(${sshcmd} "bash -c \"if [ -f ${resource_jobdir}/target.hostname ]; then cat ${resource_jobdir}/target.hostname; fi\"")
+
+            # Exit the loop if file was found and read
+            if [ -n "${target_hostname}" ]; then
+              echo "Target's hostname found: ${target_hostname}"
+              break
+            fi
+
+            # Wait before the next check
+            sleep 5
+          done
+          job_id=$(${sshcmd} cat ${resource_jobdir}/job.id)
+          if [ -z "${job_id}" ]; then
+            echo "Error: SLURM job ID is empty!" >&2
+            exit 1
+          fi
+          target_hostname=$(${sshcmd} squeue -j "${job_id}" --noheader --format="%N")
+          echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
+
+      - name: Get Remote Port
+        early-cancel: any-job-failed
+        env:
+          sshcmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ inputs.pwrl_host.resource.ip }}
+        run: |
+          source resources/host/inputs.sh
+          while true; do
+            echo "Waiting for service port file..."
+
+            # Check if the service.port file exists and read its contents
+            remote_port=$(${sshcmd} "bash -c \"if [ -f ${resource_jobdir}/service.port ]; then cat ${resource_jobdir}/service.port; fi\"")
+
+            # Exit the loop if remote_port is successfully set (file was found and read)
+            if [ -n "$remote_port" ]; then
+              echo "Service port found: $remote_port"
+              break
+            fi
+
+            # Wait before the next check
+            sleep 5
+          done
+          echo "remote_port=${remote_port}"  | tee -a $OUTPUTS
+      - name: Waiting for Server to Start
+        early-cancel: any-job-failed
+        env:
+          sshcmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ inputs.pwrl_host.resource.ip }}
+          remote_port: ${{ needs.create_session.outputs.remote_port }}
+          remote_host: ${{ needs.create_session.outputs.target_hostname }}
+        run: |
+          TIMEOUT=5
+          RETRY_INTERVAL=3
+
+          # Function to check if server is listening
+          check_server() {
+              ${sshcmd} "curl --silent --connect-timeout \"$TIMEOUT\" \"http://${remote_host}:${remote_port}\"" >/dev/null 2>&1
+              return $?
+          }
+
+          # Main loop
+          attempt=1
+          while true; do
+              echo "Attempt $attempt: Checking if server is listening on ${remote_host}:${remote_port}..."
+              
+              if check_server; then
+                  # Sleep to wait for jupyterlab after nginx connects
+                  sleep 20
+                  echo "Success: Server is listening on ${remote_host}:${remote_port}!"
+                  exit 0
+              else
+                  echo "Server not responding. Retrying in ${RETRY_INTERVAL} seconds..."
+                  sleep "$RETRY_INTERVAL"
+                  ((attempt++))
+              fi
+          done
+      - name: Select Local Port
+        early-cancel: any-job-failed
+        run: |
+          local_port=$(pw agent open-port)
+          echo "local_port=${local_port}"  | tee -a $OUTPUTS
+      - name: Set URL SLUG
+        early-cancel: any-job-failed
+        run: |
+          echo "slug=lab"  | tee -a $OUTPUTS
+      - name: Expose Port
+        early-cancel: any-job-failed
+        uses: parallelworks/update-session
+        with:
+          remotePort: '${{ needs.create_session.outputs.remote_port }}'
+          localPort: '${{ needs.create_session.outputs.local_port }}'
+          remoteHost: '${{ needs.create_session.outputs.target_hostname }}'
+          slug: '${{ needs.create_session.outputs.slug }}'
+          target: ${{ inputs.pwrl_host.resource.id }}
+          name: ${{ sessions.session }}
 
 'on':
   execute:
@@ -114,14 +283,14 @@ jobs:
         collapsed: false
       service:
         type: group
-        label: Jupyter Notebook Settings
+        label: Jupyter Lab Settings
         items:
           name:
             type: string
             hidden: true
             default: jupyterlab-host
           password:
-            label: Password for notebook session
+            label: Password for Jupyter Lab session
             type: password
             optional: true
             hidden: true
@@ -131,9 +300,9 @@ jobs:
             label: Directory to start Jupyter Lab GUI
             type: string
             default: __HOME__
-            tooltip: This is the directory that you start with when the JupyterHub graphical user interface starts. The default value here is your home directory.
+            tooltip: This is the directory that you start with when the Jupyter graphical user interface starts. The default value here is your home directory.
           conda_install:
-            label: Install Jupyter-Notebook If Not There?
+            label: Install Jupyter-Lab If Not There?
             type: boolean
             default: true
             tooltip: Select Yes to install Jupyter in miniconda environment and No to load an existing python environment
@@ -168,19 +337,21 @@ jobs:
             ignore: ${{ .hidden }}
             tooltip: Environment to active. The base environment enables changing kernel to other environments!
           load_env_tag_cloud:
-            label: Command to load Jupyter Notebook to the PATH
+            label: Command to load Jupyter Lab to the PATH
             type: string
             default: source __HOME__/pw/software/.miniconda3c/etc/profile.d/conda.sh; conda activate base
             hidden: ${{ inputs.service.conda_install == true || ('existing' == inputs.pwrl_host.resource.provider &&  inputs.service.use_conda == false) }}
             optional: ${{ .hidden }}
             ignore: ${{ .hidden }}
+            tooltip: Use a bash command
           load_env_tag_existing:
-            label: Command to load Jupyter Notebook
+            label: Command to load Jupyter Lab to the PATH
             type: string
             default: module load intelpython; export PATH=$PATH:/home/${USER}/.local/bin
             hidden: ${{ 'existing' != inputs.pwrl_host.resource.provider ||  inputs.service.use_conda == true }}
             optional: ${{ .hidden }}
             ignore: ${{ .hidden }}
+            tooltip: Use a bash command
           install_instructions_tag_cloud:
             label: Select Jupyter Lab Installation
             type: dropdown
