Saving session runner v1.3 and releasing v1.4

diff --git a/workflow/session_runner/v1.3/emed.yaml b/workflow/session_runner/v1.3/emed.yaml
--- a/workflow/session_runner/v1.3/emed.yaml
+++ b/workflow/session_runner/v1.3/emed.yaml
@@ -7,7 +7,7 @@ jobs:
       remoteHost: ${{ inputs.resource.ip }}
     steps:
       - name: Controller Preprocessing
-        run: |
+        run: | 
           set -x
           # This script prepares the target host and always runs in the controller node
           cp ${{ inputs.service.inputs_sh }} ${{ inputs.service.rundir }}/controller-preprocessing-${PW_JOB_ID}.sh
@@ -36,7 +36,6 @@ jobs:
               trap - EXIT INT TERM HUP QUIT USR1 USR2 PIPE
               echo "$(date) Cleaning up..."
               mv cancel.sh cancel.sh.submitted
-              echo "echo Cleanup script was already executed" > cancel.sh
               bash cancel.sh.submitted
               kill -- -$$
           }
@@ -49,6 +48,10 @@ jobs:
           echo
           touch job.started
           EOF
+          if ! [ -f "${{ inputs.service.start_service_script }}" ]; then
+              echo "$(date) ERROR: Service start script not found at ${{ inputs.service.start_service_script }}"
+              exit 1
+          fi
           cat ${{ inputs.service.start_service_script }} >> ${{ inputs.service.rundir }}/start-service-${PW_JOB_ID}.sh
 
   script_submitter:
@@ -58,7 +61,7 @@ jobs:
     ssh:
       remoteHost: ${{ inputs.resource.ip }}
     steps:
-      - uses: marketplace/script_submitter/v3.6
+      - uses: marketplace/script_submitter/v3.5
         early-cancel: any-job-failed
         with:
           resource: ${{ inputs.resource }}
@@ -69,14 +72,19 @@ jobs:
           define_cleanup_script: true
           cleanup_script_path: ${{ inputs.service.rundir }}/cancel.sh
           scheduler: ${{ inputs.cluster.scheduler }}
-          use_scheduler_agent: false
           slurm:
-            is_enabled: ${{ inputs.cluster.slurm.is_enabled }}
-            partition: ${{ inputs.cluster.slurm.partition }}
-            scheduler_directives: ${{ inputs.cluster.slurm.scheduler_directives }}
+            is_disabled: ${{ inputs.cluster.slurm.is_disabled }}
+            slurm_options: ${{ inputs.cluster.slurm.slurm_options }}
+            partition_default: ${{ inputs.cluster.slurm.partition_default }}
+            partition_hpc4: ${{ inputs.cluster.slurm.partition_hpc4 }}
+            cpus_per_task: ${{ inputs.cluster.slurm.cpus_per_task }}
+            mem: ${{ inputs.cluster.slurm.mem }}
+            gres_gpu_default: ${{ inputs.cluster.slurm.gres_gpu_default }}
+            gres_gpu_hpc4: ${{ inputs.cluster.slurm.gres_gpu_hpc4 }}
             time: ${{ inputs.cluster.slurm.time }}
+            scheduler_directives: ${{ inputs.cluster.slurm.scheduler_directives }}
           pbs:
-            is_enabled: ${{ inputs.cluster.pbs.is_enabled }}
+            is_disabled: ${{ inputs.cluster.pbs.is_disabled }}
             scheduler_directives: ${{ inputs.cluster.pbs.scheduler_directives }}
       - name: Notify job ended
         early-cancel: any-job-failed
@@ -85,7 +93,6 @@ jobs:
           pwd
           touch job.ended
           ls -lat job.ended
-
   wait_for_job_start:
     working-directory: ${{ inputs.service.rundir }}
     needs:
@@ -109,7 +116,7 @@ jobs:
         early-cancel: any-job-failed
         run: |
           set -x
-          HOSTNAME=$(cat HOSTNAME)
+          HOSTNAME=$(cat HOSTNAME | cut -d'.' -f1)
           echo "HOSTNAME=${HOSTNAME}" | tee -a $OUTPUTS
 
           if [ -z "${HOSTNAME}" ]; then
@@ -158,6 +165,7 @@ jobs:
               
               if check_server; then
                   echo "$(date) Success: Server is listening on ${remote_host}:${remote_port}!"
+                  sleep 30
                   exit 0
               elif [ -f job.ended ]; then
                   echo "$(date) Job was completed. Exiting... "
@@ -189,7 +197,7 @@ jobs:
         tooltip: Resource to host the service
       cluster:
         hidden: ${{ inputs.resource.schedulerType == '' }}
-        ignore: ${{ inputs.resource.schedulerType == ''  }}
+        ignore: ${{ inputs.resource.schedulerType == '' }}
         type: group
         label: Compute Cluster Settings
         items:
@@ -203,20 +211,86 @@ jobs:
           slurm:
             type: group
             label: SLURM Directives
-            hidden: ${{ inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
-            ignore: ${{ inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
+            hidden: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
+            ignore: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
             items:
-              is_enabled:
+              slurm_options:
+                type: dropdown
+                label: Select Cluster
+                optional: true
+                default: ''
+                options:
+                  - value: ''
+                    label: Default
+                  - value: 'hpc4'
+                    label: HPC4
+              is_disabled:
                 type: boolean
                 hidden: true
-                default: true
-                label: Is SLURM Enabled? Yes, unless the slurm section is hidden and ignored
-              partition:
+                default: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
+                label: Is SLURM disabled?
+              partition_default:
                 type: slurm-partitions
                 label: SLURM partition
+                ignore: ${{ 'hpc4' == inputs.cluster.slurm.slurm_options }}
+                hidden: ${{ .ignore }}
                 optional: true
                 resource: ${{ inputs.resource }}
-                tooltip: Select a partition from the drop down menu.
+                tooltip: Select a partition from the drop down menu. Leave empty to let SLURM pick a partition.
+              partition_hpc4:
+                type: dropdown
+                label: SLURM partition
+                optional: true
+                tooltip: Select a partition from the drop down menu. Leave empty to let SLURM pick a partition.
+                ignore: ${{ 'hpc4' != inputs.cluster.slurm.slurm_options }}
+                hidden: ${{ .ignore }}
+                default: normal
+                options:
+                  - normal
+                  - gpu
+                  - gpu-h200
+                  - gpu-quick
+                  - ht
+                  - large-mem
+                  - quick
+                  - test
+                  - unlimited
+              cpus_per_task:
+                type: number
+                label: CPUs per task
+                min: 1
+                max: 32
+                default: 1
+                tooltip: '--cpus-per-task=value slurm directive'
+                ignore: ${{ 'existing' != inputs.resource.provider }}
+                hidden: ${{ .ignore }}
+              mem:
+                type: string
+                label: Minimum total memory required
+                default: 8GB
+                tooltip: '--mem=value slurm directive'
+                hidden: ${{ 'existing' != inputs.resource.provider }}
+                ignore: ${{ .hidden }}
+                optional: true
+              gres_gpu_default:
+                type: number
+                label: Number of GPUs
+                ignore: ${{ ( inputs.cluster.slurm.partition_default != 'gpu' && inputs.cluster.slurm.partition_default != 'gpu-quick' ) || 'existing' != inputs.resource.provider  }}
+                hidden: ${{ .ignore }}
+                min: 1
+                max: 4
+                default: 1
+                tooltip: '--gres=gpu:X slurm directive'
+              gres_gpu_hpc4:
+                type: number
+                label: Number of GPUs
+                hidden: ${{ ( inputs.cluster.slurm.partition_hpc4 != 'gpu' && inputs.cluster.slurm.partition_hpc4 != 'gpu-quick' && inputs.cluster.slurm.partition_hpc4 != 'gpu-h200' ) || 'existing' != inputs.resource.provider  }}
+                ignore: ${{ .hidden }}
+                optional: ${{ .hidden }}
+                min: 1
+                max: 4
+                default: 1
+                tooltip: '--gres=gpu:X slurm directive'
               time:
                 label: Walltime
                 type: string
@@ -233,10 +307,11 @@ jobs:
             hidden: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
             ignore: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
             items:
-              is_enabled:
+              is_disabled:
                 type: boolean
                 hidden: true
-                label: Is PBS enabled? Yes, unless the pbs section is hidden and ignored
+                default: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
+                label: Is PBS disabled?
               scheduler_directives:
                 label: Scheduler Directives
                 type: editor
