Debug

diff --git a/workflow/yamls/jupyter-host/emed.yaml b/workflow/yamls/jupyter-host/emed.yaml
--- a/workflow/yamls/jupyter-host/emed.yaml
+++ b/workflow/yamls/jupyter-host/emed.yaml
@@ -5,6 +5,7 @@ sessions:
     useTLS: false
     redirect: true
 
+
 jobs:
   preprocessing:
     steps:
@@ -32,18 +33,15 @@ jobs:
     steps:
       - name: Create Controller Session Script
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype }}
+        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype_tag_cloud }}
         run: ./utils/steps-v3/controller/create_session_script.sh
       - name: Launch and Monitor Controller Job
-        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype }}
+        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype_tag_cloud }}
         run: ./utils/steps-v3/controller/launch_and_monitor_job.sh
-        cleanup: |
-          if [[ "${{ inputs.pwrl_host.jobschedulertype }}" == "CONTROLLER" ]]; then
-            ./kill.sh
-          fi
+        cleanup: ./kill.sh
       - name: Clean and Exit
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype }}
+        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype_tag_cloud }}
         run: ./utils/steps-v3/clean_and_exit.sh
   compute_job:
     needs:
@@ -51,18 +49,15 @@ jobs:
     steps:
       - name: Create Compute Session Script
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype }}
+        if: ${{ 'existing' == inputs.pwrl_host.resource.provider || 'CONTROLLER' != inputs.pwrl_host.jobschedulertype_tag_cloud }}
         run: ./utils/steps-v3/compute/create_session_script.sh
       - name: Launch and Monitor Compute Job
-        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype }}
+        if: ${{ 'existing' == inputs.pwrl_host.resource.provider || 'CONTROLLER' != inputs.pwrl_host.jobschedulertype_tag_cloud }}
         run: ./utils/steps-v3/compute/launch_and_monitor_job.sh
-        cleanup: |
-          if [[ "${{ inputs.pwrl_host.jobschedulertype }}" != "CONTROLLER" ]]; then
-            ./kill.sh
-          fi
+        cleanup: ./kill.sh
       - name: Clean and Exit
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype }}
+        if: ${{ 'existing' == inputs.pwrl_host.resource.provider || 'CONTROLLER' != inputs.pwrl_host.jobschedulertype_tag_cloud }}
         run: ./utils/steps-v3/clean_and_exit.sh
   create_session:
     needs:
@@ -75,16 +70,15 @@ jobs:
           echo "session_name=${session_name}" | tee -a $OUTPUTS
       - name: Get Controller Hostname
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype }}
+        if: ${{ 'CONTROLLER' == inputs.pwrl_host.jobschedulertype_tag_cloud }} 
         env:
           sshcmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ inputs.pwrl_host.resource.ip }}
         run: |
           target_hostname=$(${sshcmd} hostname)
           echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
-
       - name: Get Compute Hostname
         early-cancel: any-job-failed
-        if: ${{ 'SLURM' == inputs.pwrl_host.jobschedulertype || 'PBS' == inputs.pwrl_host.jobschedulertype }}
+        if: ${{ 'SLURM' == inputs.pwrl_host.jobschedulertype_tag_existing || 'SLURM' == inputs.pwrl_host.jobschedulertype_tag_cloud }}
         env:
           sshcmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ inputs.pwrl_host.resource.ip }}
         run: |
@@ -106,16 +100,13 @@ jobs:
             # Wait before the next check
             sleep 5
           done
-          if [[ "${{ inputs.pwrl_host.jobschedulertype }}" == "SLURM" ]]; then
-            job_id=$(${sshcmd} cat ${resource_jobdir}/job.id)
-            if [ -z "${job_id}" ]; then
-              echo "Error: SLURM job ID is empty!" >&2
-              exit 1
-            fi
-            target_hostname=$(${sshcmd} squeue -j "${job_id}" --noheader --format="%N")
+          job_id=$(${sshcmd} cat ${resource_jobdir}/job.id)
+          if [ -z "${job_id}" ]; then
+            echo "Error: SLURM job ID is empty!" >&2
+            exit 1
           fi
+          target_hostname=$(${sshcmd} squeue ${inputs.pwrl_host.slurm_options} -j "${job_id}" --noheader --format="%N")
           echo "target_hostname=${target_hostname}"  | tee -a $OUTPUTS
-
       - name: Get Remote Port
         early-cancel: any-job-failed
         env:
@@ -160,7 +151,7 @@ jobs:
               echo "Attempt $attempt: Checking if server is listening on ${remote_host}:${remote_port}..."
               
               if check_server; then
-                  # Sleep to wait for jupyter after nginx connects
+                  # Sleep to wait for jupyterlab after nginx connects
                   sleep 20
                   echo "Success: Server is listening on ${remote_host}:${remote_port}!"
                   exit 0
@@ -170,11 +161,6 @@ jobs:
                   ((attempt++))
               fi
           done
-      - name: Select Local Port
-        early-cancel: any-job-failed
-        run: |
-          local_port=$(pw agent open-port)
-          echo "local_port=${local_port}"  | tee -a $OUTPUTS
       - name: Set URL SLUG
         early-cancel: any-job-failed
         run: |
