replace !== with !=

diff --git a/workflow/yamls/k8s/ollama-openwebui/general.yaml b/workflow/yamls/k8s/ollama-openwebui/general.yaml
--- a/workflow/yamls/k8s/ollama-openwebui/general.yaml
+++ b/workflow/yamls/k8s/ollama-openwebui/general.yaml
@@ -14,59 +14,59 @@ jobs:
         early-cancel: any-job-failed
         run: pw kube auth ${{ inputs.k8s.cluster }}
   prepare_k8s_pvc:
-      needs:
-        - auth_k8s
-      steps:
-        - name: Creating New PVC YAML
-          early-cancel: any-job-failed
-          if: ${{ inputs.k8s.volumes.pvc === New }}
-          run: |
-            if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
-              pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
-            else
-              job_number=$(pwd | rev | cut -d "/" -f1 | rev)
-              workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
-              pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+    needs:
+      - auth_k8s
+    steps:
+      - name: Creating New PVC YAML
+        early-cancel: any-job-failed
+        if: ${{ inputs.k8s.volumes.pvc === New }}
+        run: |
+          if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
+            pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
+          else
+            job_number=$(pwd | rev | cut -d "/" -f1 | rev)
+            workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
+            pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+          fi
+          pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
+          if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
+            default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
+            if [ $? -ne 0 ]; then
+              echo "WARNING: Could not obtain default storageClass with command:"
+              echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
+              echo "         You might need to provide a storage class input"
+            elif [ -z "${default_class}" ]; then
+              echo "ERROR: No default storage class found. You must specify one explicitly."
+              exit 1
             fi
-            pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
-            if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
-              default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
-              if [ $? -ne 0 ]; then
-                echo "WARNING: Could not obtain default storageClass with command:"
-                echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
-                echo "         You might need to provide a storage class input"
-              elif [ -z "${default_class}" ]; then
-                echo "ERROR: No default storage class found. You must specify one explicitly."
-                exit 1
-              fi
-            else
-              storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
-            fi
-            echo "${pvc_name}" > pvc_name
-            cat <<EOF > pvc.yaml
-            apiVersion: v1
-            kind: PersistentVolumeClaim
-            metadata:
-              name: ${pvc_name}
-              namespace: ${{ inputs.k8s.namespace }}
-            spec:
-              accessModes:
-                - ReadWriteOnce
-              resources:
-                requests:
-                  storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
-              ${storageClassName} 
-            EOF
-            cat pvc.yaml
-        - name: Dry Run PVC
-          early-cancel: any-job-failed
-          if: ${{ inputs.k8s.volumes.pvc === New }}
-          run: |
-            echo "Performing dry run..."
-            kubectl apply -f pvc.yaml --dry-run=client
-        - name: Dummy
-          early-cancel: any-job-failed
-          run: echo Dummy
+          else
+            storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
+          fi
+          echo "${pvc_name}" > pvc_name
+          cat <<EOF > pvc.yaml
+          apiVersion: v1
+          kind: PersistentVolumeClaim
+          metadata:
+            name: ${pvc_name}
+            namespace: ${{ inputs.k8s.namespace }}
+          spec:
+            accessModes:
+              - ReadWriteOnce
+            resources:
+              requests:
+                storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
+            ${storageClassName} 
+          EOF
+          cat pvc.yaml
+      - name: Dry Run PVC
+        early-cancel: any-job-failed
+        if: ${{ inputs.k8s.volumes.pvc === New }}
+        run: |
+          echo "Performing dry run..."
+          kubectl apply -f pvc.yaml --dry-run=client
+      - name: Dummy
+        early-cancel: any-job-failed
+        run: echo Dummy
   prepare_k8s_deployment:
     needs:
       - prepare_k8s_pvc
@@ -407,20 +407,20 @@ jobs:
                 type: kubernetes-pvc
                 clusterName: ${{ inputs.k8s.cluster }}
                 namespace: ${{ inputs.k8s.namespace }}
-                hidden: ${{ inputs.k8s.volumes.pvc !== Existing }}
+                hidden: ${{ inputs.k8s.volumes.pvc != Existing }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
               pvc_storage_size:
                 label: Enter PVC Size
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc !== New }}
+                hidden: ${{ inputs.k8s.volumes.pvc != New }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
                 default: 20Gi
               pvc_storage_class:
                 label: Enter PVC Storage Class
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc !== New }}
+                hidden: ${{ inputs.k8s.volumes.pvc != New }}
                 ignore: ${{ .hidden }}
                 optional: true
                 tooltip: Leave blank to use the default storage class configured in the cluster.
@@ -428,14 +428,14 @@ jobs:
                 label: Persist PVC After Completion
                 type: boolean
                 default: false
-                hidden: ${{ inputs.k8s.volumes.pvc !== 'New' }}
+                hidden: ${{ inputs.k8s.volumes.pvc != 'New' }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
                 tooltip: If true, the PVC will persist after the job is canceled or completed. If false, it will be deleted.
               pvc_name:
                 label: Enter PVC Name
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc_persist === false || inputs.k8s.volumes.pvc !== New  }}
+                hidden: ${{ inputs.k8s.volumes.pvc_persist === false || inputs.k8s.volumes.pvc != New  }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
           ollama_resources:
@@ -490,7 +490,7 @@ jobs:
                   gpu_resource_key:
                     label: Custom GPU Resource Key
                     type: string
-                    hidden: ${{ inputs.k8s.ollama_resources.limits.select_gpu !== Custom }}
+                    hidden: ${{ inputs.k8s.ollama_resources.limits.select_gpu != Custom }}
                     ignore: ${{ .hidden }}
                     tooltip: |
                       Specify a custom GPU resource key for Kubernetes, such as:
diff --git a/workflow/yamls/mlflow/general_k8s.yaml b/workflow/yamls/mlflow/general_k8s.yaml
--- a/workflow/yamls/mlflow/general_k8s.yaml
+++ b/workflow/yamls/mlflow/general_k8s.yaml
@@ -18,10 +18,10 @@ jobs:
       - name: Process Inputs
         early-cancel: any-job-failed
         if: ${{ inputs.targetType === 'compute-cluster' }}
-        run: | 
+        run: |
           set -e
           echo "export basepath=/me/session/${PW_USER}/${{ sessions.session }}"  >> resources/host/inputs.sh
-          ./utils/steps-v3/preprocessing/process_inputs_sh.sh 
+          ./utils/steps-v3/preprocessing/process_inputs_sh.sh
       - name: Transfer Files to Controller
         early-cancel: any-job-failed
         if: ${{ inputs.targetType === 'compute-cluster' }}
@@ -37,7 +37,7 @@ jobs:
 
   controller_job:
     needs:
-       - preprocessing
+      - preprocessing
     steps:
       - name: Create Controller Session Script
         early-cancel: any-job-failed
@@ -57,14 +57,14 @@ jobs:
 
   compute_job:
     needs:
-       - preprocessing
+      - preprocessing
     steps:
       - name: Create Compute Session Script
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' !== inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
         run: ./utils/steps-v3/compute/create_session_script.sh
-      - name:  Launch and Monitor Compute Job
-        if: ${{ 'CONTROLLER' !== inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
+      - name: Launch and Monitor Compute Job
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
         run: ./utils/steps-v3/compute/launch_and_monitor_job.sh
         cleanup: |
           if [[ "${{ inputs.pwrl_host.jobschedulertype }}" != "CONTROLLER" ]]; then
@@ -72,13 +72,12 @@ jobs:
           fi
       - name: Clean and Exit
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' !== inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
         run: ./utils/steps-v3/clean_and_exit.sh
-
 
   create_session:
     needs:
-       - preprocessing
+      - preprocessing
     steps:
       - name: Set Session Name
         early-cancel: any-job-failed
@@ -191,9 +190,9 @@ jobs:
         if: ${{ inputs.targetType === 'compute-cluster' }}
         uses: parallelworks/update-session
         with:
-          remotePort: "${{ needs.create_session.outputs.remote_port }}"
-          localPort: "${{ needs.create_session.outputs.local_port }}"
-          remoteHost: "${{ needs.create_session.outputs.target_hostname }}"
+          remotePort: '${{ needs.create_session.outputs.remote_port }}'
+          localPort: '${{ needs.create_session.outputs.local_port }}'
+          remoteHost: '${{ needs.create_session.outputs.target_hostname }}'
           target: ${{ inputs.pwrl_host.resource.id }}
           name: ${{ sessions.session }}
   auth_k8s:
@@ -203,59 +202,59 @@ jobs:
         if: ${{ inputs.targetType === 'kubernetes-cluster' }}
         run: pw kube auth ${{ inputs.k8s.cluster }}
   prepare_k8s_pvc:
-      needs:
-        - auth_k8s
-      steps:
-        - name: Creating New PVC YAML
-          early-cancel: any-job-failed
-          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-          run: |
-            if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
-              pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
-            else
-              job_number=$(pwd | rev | cut -d "/" -f1 | rev)
-              workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
-              pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+    needs:
+      - auth_k8s
+    steps:
+      - name: Creating New PVC YAML
+        early-cancel: any-job-failed
+        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+        run: |
+          if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
+            pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
+          else
+            job_number=$(pwd | rev | cut -d "/" -f1 | rev)
+            workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
+            pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+          fi
+          pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
+          if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
+            default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
+            if [ $? -ne 0 ]; then
+              echo "WARNING: Could not obtain default storageClass with command:"
+              echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
+              echo "         You might need to provide a storage class input"
+            elif [ -z "${default_class}" ]; then
+              echo "ERROR: No default storage class found. You must specify one explicitly."
+              exit 1
             fi
-            pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
-            if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
-              default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
-              if [ $? -ne 0 ]; then
-                echo "WARNING: Could not obtain default storageClass with command:"
-                echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
-                echo "         You might need to provide a storage class input"
-              elif [ -z "${default_class}" ]; then
-                echo "ERROR: No default storage class found. You must specify one explicitly."
-                exit 1
-              fi
-            else
-              storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
-            fi
-            echo "${pvc_name}" > pvc_name
-            cat <<EOF > pvc.yaml
-            apiVersion: v1
-            kind: PersistentVolumeClaim
-            metadata:
-              name: ${pvc_name}
-              namespace: ${{ inputs.k8s.namespace }}
-            spec:
-              accessModes:
-                - ReadWriteOnce
-              resources:
-                requests:
-                  storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
-              ${storageClassName} 
-            EOF
-            cat pvc.yaml
-        - name: Dry Run PVC
-          early-cancel: any-job-failed
-          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-          run: |
-            echo "Performing dry run..."
-            kubectl apply -f pvc.yaml --dry-run=client
-        - name: Dummy
-          early-cancel: any-job-failed
-          run: echo Dummy
+          else
+            storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
+          fi
+          echo "${pvc_name}" > pvc_name
+          cat <<EOF > pvc.yaml
+          apiVersion: v1
+          kind: PersistentVolumeClaim
+          metadata:
+            name: ${pvc_name}
+            namespace: ${{ inputs.k8s.namespace }}
+          spec:
+            accessModes:
+              - ReadWriteOnce
+            resources:
+              requests:
+                storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
+            ${storageClassName} 
+          EOF
+          cat pvc.yaml
+      - name: Dry Run PVC
+        early-cancel: any-job-failed
+        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+        run: |
+          echo "Performing dry run..."
+          kubectl apply -f pvc.yaml --dry-run=client
+      - name: Dummy
+        early-cancel: any-job-failed
+        run: echo Dummy
   prepare_k8s_deployment:
     needs:
       - prepare_k8s_pvc
@@ -507,7 +506,6 @@ jobs:
             resourceType: services
             resourceName: ${{ needs.create_k8s_session.outputs.service_name }}
 
-
 'on':
   execute:
     inputs:
@@ -521,7 +519,7 @@ jobs:
           - label: Kubernetes Cluster
             value: kubernetes-cluster
       pwrl_host:
-        hidden: ${{ inputs.targetType !== 'compute-cluster' }}
+        hidden: ${{ inputs.targetType != 'compute-cluster' }}
         type: group
         label: MLflow
         items:
@@ -529,7 +527,7 @@ jobs:
             type: compute-clusters
             label: Service host
             include-workspace: false
-            optional: ${{ inputs.targetType !== 'compute-cluster' }}
+            optional: ${{ inputs.targetType != 'compute-cluster' }}
             tooltip: Resource to host the service
           nports:
             type: number
@@ -552,7 +550,7 @@ jobs:
           _sch__dd_partition_e_:
             type: slurm-partitions
             label: SLURM partition
-            hidden: ${{ 'SLURM' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: true
             tooltip: Partition to submit the interactive job. Leave empty to let SLURM pick the optimal option.
@@ -560,21 +558,21 @@ jobs:
           scheduler_directives_slurm:
             type: string
             label: Scheduler directives
-            hidden: ${{ 'SLURM' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: true
             tooltip: e.g. --mem=1000;--gpus-per-node=1 - Use the semicolon character ; to separate parameters. Do not include the SBATCH keyword.
           _sch__d_q___:
             type: string
             label: PBS queue
-            hidden: ${{ 'PBS' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'PBS' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: ${{ .hidden }}
             tooltip: Queue to submit the interactive job. Must select one! Use [qstat -f -Q] to list all queues on the system
           scheduler_directives_pbs:
             type: string
             label: Scheduler directives
-            hidden: ${{ 'PBS' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'PBS' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: true
             tooltip: e.g. -l mem=1000;-l nodes=1:ppn=4 - Use the semicolon character ; to separate parameters. Do not include the PBS keyword.
@@ -582,7 +580,7 @@ jobs:
       service:
         type: group
         label: MLFlow Settings
-        hidden: ${{ inputs.targetType !== 'compute-cluster' }}
+        hidden: ${{ inputs.targetType != 'compute-cluster' }}
         items:
           name:
             type: string
@@ -620,17 +618,17 @@ jobs:
       k8s:
         type: group
         label: Kubernetes Settings
-        hidden: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+        hidden: ${{ inputs.targetType != 'kubernetes-cluster' }}
         items:
           cluster:
             label: Kubernetes cluster
             type: kubernetes-clusters
-            optional: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+            optional: ${{ inputs.targetType != 'kubernetes-cluster' }}
           namespace:
             label: Namespace
             type: kubernetes-namespaces
             clusterName: ${{ inputs.k8s.cluster }}
-            optional: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+            optional: ${{ inputs.targetType != 'kubernetes-cluster' }}
           volumes:
             type: group
             label: Volumes
@@ -655,20 +653,20 @@ jobs:
                 type: kubernetes-pvc
                 clusterName: ${{ inputs.k8s.cluster }}
                 namespace: ${{ inputs.k8s.namespace }}
-                hidden: ${{ inputs.k8s.volumes.pvc !== Existing }}
+                hidden: ${{ inputs.k8s.volumes.pvc != Existing }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
               pvc_storage_size:
                 label: Enter PVC Size
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc !== New }}
+                hidden: ${{ inputs.k8s.volumes.pvc != New }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
                 default: 10Gi
               pvc_storage_class:
                 label: Enter PVC Storage Class
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc !== New }}
+                hidden: ${{ inputs.k8s.volumes.pvc != New }}
                 ignore: ${{ .hidden }}
                 optional: true
                 tooltip: Leave blank to use the default storage class configured in the cluster.
@@ -676,14 +674,14 @@ jobs:
                 label: Persist PVC After Completion
                 type: boolean
                 default: false
-                hidden: ${{ inputs.k8s.volumes.pvc !== 'New' }}
+                hidden: ${{ inputs.k8s.volumes.pvc != 'New' }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
                 tooltip: If true, the PVC will persist after the job is canceled or completed. If false, it will be deleted.
               pvc_name:
                 label: Enter PVC Name
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc_persist === false || inputs.k8s.volumes.pvc !== New  }}
+                hidden: ${{ inputs.k8s.volumes.pvc_persist === false || inputs.k8s.volumes.pvc != New  }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
           resources:
@@ -738,7 +736,7 @@ jobs:
                   gpu_resource_key:
                     label: Custom GPU Resource Key
                     type: string
-                    hidden: ${{ inputs.k8s.resources.limits.select_gpu !== Custom }}
+                    hidden: ${{ inputs.k8s.resources.limits.select_gpu != Custom }}
                     ignore: ${{ .hidden }}
                     tooltip: |
                       Specify a custom GPU resource key for Kubernetes, such as:
@@ -760,7 +758,7 @@ jobs:
       service_k8s:
         type: group
         label: Service Settings
-        hidden: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+        hidden: ${{ inputs.targetType != 'kubernetes-cluster' }}
         items:
           image:
             label: MLFlow Image
@@ -770,4 +768,4 @@ jobs:
             label: MLFlow Port
             type: number
             default: 5000
-            tooltip: Define the port on which the MLFlow server runs inside the container. 
+            tooltip: Define the port on which the MLFlow server runs inside the container.
diff --git a/workflow/yamls/openvscode/general_k8s.yaml b/workflow/yamls/openvscode/general_k8s.yaml
--- a/workflow/yamls/openvscode/general_k8s.yaml
+++ b/workflow/yamls/openvscode/general_k8s.yaml
@@ -23,7 +23,7 @@ jobs:
           if ! [ -z ${{ org.JUICE_TOKEN }} ]; then
             echo "export JUICE_TOKEN=${{ org.JUICE_TOKEN }}"  >> resources/host/inputs.sh
           fi
-          ./utils/steps-v3/preprocessing/process_inputs_sh.sh 
+          ./utils/steps-v3/preprocessing/process_inputs_sh.sh
       - name: Transfer Files to Controller
         early-cancel: any-job-failed
         if: ${{ inputs.targetType === 'compute-cluster' }}
@@ -61,10 +61,10 @@ jobs:
     steps:
       - name: Create Compute Session Script
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' !== inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
         run: ./utils/steps-v3/compute/create_session_script.sh
       - name: Launch and Monitor Compute Job
-        if: ${{ 'CONTROLLER' !== inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
         run: ./utils/steps-v3/compute/launch_and_monitor_job.sh
         cleanup: |
           if [[ "${{ inputs.pwrl_host.jobschedulertype }}" != "CONTROLLER" ]]; then
@@ -72,7 +72,7 @@ jobs:
           fi
       - name: Clean and Exit
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' !== inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
         run: ./utils/steps-v3/clean_and_exit.sh
   create_session:
     needs:
@@ -207,59 +207,59 @@ jobs:
         if: ${{ inputs.targetType === 'kubernetes-cluster' }}
         run: pw kube auth ${{ inputs.k8s.cluster }}
   prepare_k8s_pvc:
-      needs:
-        - auth_k8s
-      steps:
-        - name: Creating New PVC YAML
-          early-cancel: any-job-failed
-          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-          run: |
-            if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
-              pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
-            else
-              job_number=$(pwd | rev | cut -d "/" -f1 | rev)
-              workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
-              pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+    needs:
+      - auth_k8s
+    steps:
+      - name: Creating New PVC YAML
+        early-cancel: any-job-failed
+        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+        run: |
+          if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
+            pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
+          else
+            job_number=$(pwd | rev | cut -d "/" -f1 | rev)
+            workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
+            pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+          fi
+          pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
+          if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
+            default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
+            if [ $? -ne 0 ]; then
+              echo "WARNING: Could not obtain default storageClass with command:"
+              echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
+              echo "         You might need to provide a storage class input"
+            elif [ -z "${default_class}" ]; then
+              echo "ERROR: No default storage class found. You must specify one explicitly."
+              exit 1
             fi
-            pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
-            if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
-              default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
-              if [ $? -ne 0 ]; then
-                echo "WARNING: Could not obtain default storageClass with command:"
-                echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
-                echo "         You might need to provide a storage class input"
-              elif [ -z "${default_class}" ]; then
-                echo "ERROR: No default storage class found. You must specify one explicitly."
-                exit 1
-              fi
-            else
-              storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
-            fi
-            echo "${pvc_name}" > pvc_name
-            cat <<EOF > pvc.yaml
-            apiVersion: v1
-            kind: PersistentVolumeClaim
-            metadata:
-              name: ${pvc_name}
-              namespace: ${{ inputs.k8s.namespace }}
-            spec:
-              accessModes:
-                - ReadWriteOnce
-              resources:
-                requests:
-                  storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
-              ${storageClassName} 
-            EOF
-            cat pvc.yaml
-        - name: Dry Run PVC
-          early-cancel: any-job-failed
-          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-          run: |
-            echo "Performing dry run..."
-            kubectl apply -f pvc.yaml --dry-run=client
-        - name: Dummy
-          early-cancel: any-job-failed
-          run: echo Dummy
+          else
+            storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
+          fi
+          echo "${pvc_name}" > pvc_name
+          cat <<EOF > pvc.yaml
+          apiVersion: v1
+          kind: PersistentVolumeClaim
+          metadata:
+            name: ${pvc_name}
+            namespace: ${{ inputs.k8s.namespace }}
+          spec:
+            accessModes:
+              - ReadWriteOnce
+            resources:
+              requests:
+                storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
+            ${storageClassName} 
+          EOF
+          cat pvc.yaml
+      - name: Dry Run PVC
+        early-cancel: any-job-failed
+        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+        run: |
+          echo "Performing dry run..."
+          kubectl apply -f pvc.yaml --dry-run=client
+      - name: Dummy
+        early-cancel: any-job-failed
+        run: echo Dummy
   prepare_k8s_deployment:
     needs:
       - prepare_k8s_pvc
@@ -294,7 +294,7 @@ jobs:
           else
             pvc_name=$(cat pvc_name)
           fi
-  
+
           cat <<EOF > app.yaml
 
           apiVersion: apps/v1
@@ -528,13 +528,13 @@ jobs:
           - label: Kubernetes Cluster
             value: kubernetes-cluster
       pwrl_host:
-        hidden: ${{ inputs.targetType !== 'compute-cluster' }}
+        hidden: ${{ inputs.targetType != 'compute-cluster' }}
         type: group
         label: Compute Settings
         items:
           resource:
             type: compute-clusters
-            optional: ${{ inputs.targetType !== 'compute-cluster' }}
+            optional: ${{ inputs.targetType != 'compute-cluster' }}
             label: Service host
             include-workspace: false
             tooltip: Resource to host the service
@@ -559,7 +559,7 @@ jobs:
           _sch__dd_partition_e_:
             type: slurm-partitions
             label: SLURM partition
-            hidden: ${{ 'SLURM' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: true
             tooltip: Partition to submit the interactive job. Leave empty to let SLURM pick the optimal option.
@@ -567,21 +567,21 @@ jobs:
           scheduler_directives_slurm:
             type: string
             label: Scheduler directives
-            hidden: ${{ 'SLURM' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: true
             tooltip: e.g. --mem=1000;--gpus-per-node=1 - Use the semicolon character ; to separate parameters. Do not include the SBATCH keyword.
           _sch__d_q___:
             type: string
             label: PBS queue
-            hidden: ${{ 'PBS' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'PBS' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: ${{ .hidden }}
             tooltip: Queue to submit the interactive job. Must select one! Use [qstat -f -Q] to list all queues on the system
           scheduler_directives_pbs:
             type: string
             label: Scheduler directives
-            hidden: ${{ 'PBS' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'PBS' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: true
             tooltip: e.g. -l mem=1000;-l nodes=1:ppn=4 - Use the semicolon character ; to separate parameters. Do not include the PBS keyword.
@@ -590,7 +590,7 @@ jobs:
         type: group
         label: VS Code Settings
         collapsed: true
-        hidden: ${{ inputs.targetType !== 'compute-cluster' }}
+        hidden: ${{ inputs.targetType != 'compute-cluster' }}
         items:
           name:
             type: string
@@ -618,17 +618,17 @@ jobs:
       k8s:
         type: group
         label: Kubernetes Settings
-        hidden: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+        hidden: ${{ inputs.targetType != 'kubernetes-cluster' }}
         items:
           cluster:
             label: Kubernetes cluster
             type: kubernetes-clusters
-            optional: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+            optional: ${{ inputs.targetType != 'kubernetes-cluster' }}
           namespace:
             label: Namespace
             type: kubernetes-namespaces
             clusterName: ${{ inputs.k8s.cluster }}
-            optional: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+            optional: ${{ inputs.targetType != 'kubernetes-cluster' }}
           volumes:
             type: group
             label: Volumes
@@ -653,20 +653,20 @@ jobs:
                 type: kubernetes-pvc
                 clusterName: ${{ inputs.k8s.cluster }}
                 namespace: ${{ inputs.k8s.namespace }}
-                hidden: ${{ inputs.k8s.volumes.pvc !== Existing }}
+                hidden: ${{ inputs.k8s.volumes.pvc != Existing }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
               pvc_storage_size:
                 label: Enter PVC Size
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc !== New }}
+                hidden: ${{ inputs.k8s.volumes.pvc != New }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
                 default: 10Gi
               pvc_storage_class:
                 label: Enter PVC Storage Class
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc !== New }}
+                hidden: ${{ inputs.k8s.volumes.pvc != New }}
                 ignore: ${{ .hidden }}
                 optional: true
                 tooltip: Leave blank to use the default storage class configured in the cluster.
@@ -674,14 +674,14 @@ jobs:
                 label: Persist PVC After Completion
                 type: boolean
                 default: false
-                hidden: ${{ inputs.k8s.volumes.pvc !== 'New' }}
+                hidden: ${{ inputs.k8s.volumes.pvc != 'New' }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
                 tooltip: If true, the PVC will persist after the job is canceled or completed. If false, it will be deleted.
               pvc_name:
                 label: Enter PVC Name
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc_persist === false || inputs.k8s.volumes.pvc !== New  }}
+                hidden: ${{ inputs.k8s.volumes.pvc_persist === false || inputs.k8s.volumes.pvc != New  }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
           resources:
@@ -736,7 +736,7 @@ jobs:
                   gpu_resource_key:
                     label: Custom GPU Resource Key
                     type: string
-                    hidden: ${{ inputs.k8s.resources.limits.select_gpu !== Custom }}
+                    hidden: ${{ inputs.k8s.resources.limits.select_gpu != Custom }}
                     ignore: ${{ .hidden }}
                     tooltip: |
                       Specify a custom GPU resource key for Kubernetes, such as:
@@ -758,7 +758,7 @@ jobs:
       service_k8s:
         type: group
         label: Service Settings
-        hidden: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+        hidden: ${{ inputs.targetType != 'kubernetes-cluster' }}
         items:
           image:
             label: Code Server Image
@@ -772,7 +772,7 @@ jobs:
             tooltip: Define the port on which the Code Server runs inside the container. Default is 8080.
           password:
             label: Password
-            optional: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+            optional: ${{ inputs.targetType != 'kubernetes-cluster' }}
             type: password
             tooltip: Type in a password
           github_token:
@@ -783,7 +783,7 @@ jobs:
         type: group
         label: Attached GPU Settings
         collapsed: true
-        hidden: ${{ org.JUICE_TOKEN == "" || inputs.targetType !== 'compute-cluster' }}
+        hidden: ${{ org.JUICE_TOKEN == "" || inputs.targetType != 'compute-cluster' }}
         items:
           use_juice:
             label: Enable Juice?
@@ -796,14 +796,14 @@ jobs:
             hidden: ${{ inputs.juice.use_juice == false }}
             ignore: ${{ .hidden }}
             optional: true
-            tooltip:  Comma separated list of pool ids from which to allocate the session resources, when empty any available pool you have access to is used
+            tooltip: Comma separated list of pool ids from which to allocate the session resources, when empty any available pool you have access to is used
           vram:
             label: VRAM
             type: string
             hidden: ${{ inputs.juice.use_juice == false }}
             ignore: ${{ .hidden }}
             optional: true
-            tooltip:  Amount of VRAM requested in gibibytes. Can return a session with fewer bytes if there is not enough space on the device. Suffixes can be provided for convenience. E.g. 4 GiB (default "0")
+            tooltip: Amount of VRAM requested in gibibytes. Can return a session with fewer bytes if there is not enough space on the device. Suffixes can be provided for convenience. E.g. 4 GiB (default "0")
           cmd_args:
             label: Juice Run Command Arguments
             type: string
diff --git a/workflow/yamls/pgadmin4/general_k8s.yaml b/workflow/yamls/pgadmin4/general_k8s.yaml
--- a/workflow/yamls/pgadmin4/general_k8s.yaml
+++ b/workflow/yamls/pgadmin4/general_k8s.yaml
@@ -20,7 +20,7 @@ jobs:
         run: |
           set -e
           echo "export basepath=/me/session/${PW_USER}/${{ sessions.session }}"  >> resources/host/inputs.sh
-          ./utils/steps-v3/preprocessing/process_inputs_sh.sh 
+          ./utils/steps-v3/preprocessing/process_inputs_sh.sh
       - name: Transfer Files to Controller
         early-cancel: any-job-failed
         if: ${{ inputs.targetType === 'compute-cluster' }}
@@ -58,10 +58,10 @@ jobs:
     steps:
       - name: Create Compute Session Script
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' !== inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
         run: ./utils/steps-v3/compute/create_session_script.sh
       - name: Launch and Monitor Compute Job
-        if: ${{ 'CONTROLLER' !== inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
         run: ./utils/steps-v3/compute/launch_and_monitor_job.sh
         cleanup: |
           if [[ "${{ inputs.pwrl_host.jobschedulertype }}" != "CONTROLLER" ]]; then
@@ -69,7 +69,7 @@ jobs:
           fi
       - name: Clean and Exit
         early-cancel: any-job-failed
-        if: ${{ 'CONTROLLER' !== inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
+        if: ${{ 'CONTROLLER' != inputs.pwrl_host.jobschedulertype && inputs.targetType === 'compute-cluster' }}
         run: ./utils/steps-v3/clean_and_exit.sh
   create_session:
     needs:
@@ -197,59 +197,59 @@ jobs:
         if: ${{ inputs.targetType === 'kubernetes-cluster' }}
         run: pw kube auth ${{ inputs.k8s.cluster }}
   prepare_k8s_pvc:
-      needs:
-        - auth_k8s
-      steps:
-        - name: Creating New PVC YAML
-          early-cancel: any-job-failed
-          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-          run: |
-            if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
-              pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
-            else
-              job_number=$(pwd | rev | cut -d "/" -f1 | rev)
-              workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
-              pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+    needs:
+      - auth_k8s
+    steps:
+      - name: Creating New PVC YAML
+        early-cancel: any-job-failed
+        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+        run: |
+          if [[ ${{ inputs.k8s.volumes.pvc_persist }} == "true" ]]; then
+            pvc_name="${{ inputs.k8s.volumes.pvc_name }}"
+          else
+            job_number=$(pwd | rev | cut -d "/" -f1 | rev)
+            workflow_name=$(pwd | rev | cut -d "/" -f2 | rev)
+            pvc_name=$(echo "${PW_USER}${workflow_name}${job_number}" | sed 's|_||g' | sed 's|\.||g' | tr '[:upper:]' '[:lower:]' | tail -c 56)-pvc
+          fi
+          pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
+          if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
+            default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
+            if [ $? -ne 0 ]; then
+              echo "WARNING: Could not obtain default storageClass with command:"
+              echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
+              echo "         You might need to provide a storage class input"
+            elif [ -z "${default_class}" ]; then
+              echo "ERROR: No default storage class found. You must specify one explicitly."
+              exit 1
             fi
-            pvc_storage_class=${{ inputs.k8s.volumes.pvc_storage_class }} 
-            if [ -z "${pvc_storage_class}" ] || [[ "${pvc_storage_class}" == "undefined" ]]; then
-              default_class=$(kubectl get storageclass -n ${{ inputs.k8s.namespace }} | grep '(default)')
-              if [ $? -ne 0 ]; then
-                echo "WARNING: Could not obtain default storageClass with command:"
-                echo "         kubectl get storageclass -n ${{ inputs.k8s.namespace }}"
-                echo "         You might need to provide a storage class input"
-              elif [ -z "${default_class}" ]; then
-                echo "ERROR: No default storage class found. You must specify one explicitly."
-                exit 1
-              fi
-            else
-              storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
-            fi
-            echo "${pvc_name}" > pvc_name
-            cat <<EOF > pvc.yaml
-            apiVersion: v1
-            kind: PersistentVolumeClaim
-            metadata:
-              name: ${pvc_name}
-              namespace: ${{ inputs.k8s.namespace }}
-            spec:
-              accessModes:
-                - ReadWriteOnce
-              resources:
-                requests:
-                  storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
-              ${storageClassName} 
-            EOF
-            cat pvc.yaml
-        - name: Dry Run PVC
-          early-cancel: any-job-failed
-          if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
-          run: |
-            echo "Performing dry run..."
-            kubectl apply -f pvc.yaml --dry-run=client
-        - name: Dummy
-          early-cancel: any-job-failed
-          run: echo Dummy
+          else
+            storageClassName="storageClassName: ${{ inputs.k8s.volumes.pvc_storage_class }}"
+          fi
+          echo "${pvc_name}" > pvc_name
+          cat <<EOF > pvc.yaml
+          apiVersion: v1
+          kind: PersistentVolumeClaim
+          metadata:
+            name: ${pvc_name}
+            namespace: ${{ inputs.k8s.namespace }}
+          spec:
+            accessModes:
+              - ReadWriteOnce
+            resources:
+              requests:
+                storage: ${{ inputs.k8s.volumes.pvc_storage_size }}  
+            ${storageClassName} 
+          EOF
+          cat pvc.yaml
+      - name: Dry Run PVC
+        early-cancel: any-job-failed
+        if: ${{ inputs.targetType === 'kubernetes-cluster' && inputs.k8s.volumes.pvc === New  }}
+        run: |
+          echo "Performing dry run..."
+          kubectl apply -f pvc.yaml --dry-run=client
+      - name: Dummy
+        early-cancel: any-job-failed
+        run: echo Dummy
   prepare_k8s_deployment:
     needs:
       - prepare_k8s_pvc
@@ -284,7 +284,7 @@ jobs:
           else
             pvc_name=$(cat pvc_name)
           fi
-  
+
           cat <<EOF > app.yaml
 
           apiVersion: apps/v1
@@ -498,7 +498,7 @@ jobs:
         if: ${{ inputs.targetType === 'kubernetes-cluster' }}
         uses: parallelworks/update-session
         with:
-          remotePort: "80"
+          remotePort: '80'
           name: ${{ sessions.session }}
           targetInfo:
             name: ${{ inputs.k8s.cluster }}
@@ -518,13 +518,13 @@ jobs:
           - label: Kubernetes Cluster
             value: kubernetes-cluster
       pwrl_host:
-        hidden: ${{ inputs.targetType !== 'compute-cluster' }}
+        hidden: ${{ inputs.targetType != 'compute-cluster' }}
         type: group
         label: Compute Settings
         items:
           resource:
             type: compute-clusters
-            optional: ${{ inputs.targetType !== 'compute-cluster' }}
+            optional: ${{ inputs.targetType != 'compute-cluster' }}
             label: Service host
             include-workspace: false
             tooltip: Resource to host the service
@@ -549,7 +549,7 @@ jobs:
           _sch__dd_partition_e_:
             type: slurm-partitions
             label: SLURM partition
-            hidden: ${{ 'SLURM' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: true
             tooltip: Partition to submit the interactive job. Leave empty to let SLURM pick the optimal option.
@@ -557,21 +557,21 @@ jobs:
           scheduler_directives_slurm:
             type: string
             label: Scheduler directives
-            hidden: ${{ 'SLURM' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: true
             tooltip: e.g. --mem=1000;--gpus-per-node=1 - Use the semicolon character ; to separate parameters. Do not include the SBATCH keyword.
           _sch__d_q___:
             type: string
             label: PBS queue
-            hidden: ${{ 'PBS' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'PBS' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: ${{ .hidden }}
             tooltip: Queue to submit the interactive job. Must select one! Use [qstat -f -Q] to list all queues on the system
           scheduler_directives_pbs:
             type: string
             label: Scheduler directives
-            hidden: ${{ 'PBS' !== inputs.pwrl_host.jobschedulertype }}
+            hidden: ${{ 'PBS' != inputs.pwrl_host.jobschedulertype }}
             ignore: ${{ .hidden }}
             optional: true
             tooltip: e.g. -l mem=1000;-l nodes=1:ppn=4 - Use the semicolon character ; to separate parameters. Do not include the PBS keyword.
@@ -580,7 +580,7 @@ jobs:
         type: group
         label: Pgadmin4 Settings
         collapsed: false
-        hidden: ${{ inputs.targetType !== 'compute-cluster' }}
+        hidden: ${{ inputs.targetType != 'compute-cluster' }}
         items:
           name:
             type: string
@@ -595,32 +595,31 @@ jobs:
             label: Docker mount volumes
             type: string
             optional: true
-            tooltip: 
-              "Type in the mount volume options for the docker command. E.g.: -v /mnt:/mnt -v /data:/data"
+            tooltip: 'Type in the mount volume options for the docker command. E.g.: -v /mnt:/mnt -v /data:/data'
           email:
             label: Email
-            optional: ${{ inputs.targetType !== 'compute-cluster' }}
+            optional: ${{ inputs.targetType != 'compute-cluster' }}
             type: string
             tooltip: Enter email for PGADMIN_DEFAULT_EMAIL variable
           password:
             label: Password
-            optional: ${{ inputs.targetType !== 'compute-cluster' }}
+            optional: ${{ inputs.targetType != 'compute-cluster' }}
             type: password
             tooltip: Enter password for PGADMIN_DEFAULT_PASSWORD variable
       k8s:
         type: group
         label: Kubernetes Settings
-        hidden: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+        hidden: ${{ inputs.targetType != 'kubernetes-cluster' }}
         items:
           cluster:
             label: Kubernetes cluster
             type: kubernetes-clusters
-            optional: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+            optional: ${{ inputs.targetType != 'kubernetes-cluster' }}
           namespace:
             label: Namespace
             type: kubernetes-namespaces
             clusterName: ${{ inputs.k8s.cluster }}
-            optional: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+            optional: ${{ inputs.targetType != 'kubernetes-cluster' }}
           volumes:
             type: group
             label: Volumes
@@ -645,20 +644,20 @@ jobs:
                 type: kubernetes-pvc
                 clusterName: ${{ inputs.k8s.cluster }}
                 namespace: ${{ inputs.k8s.namespace }}
-                hidden: ${{ inputs.k8s.volumes.pvc !== Existing }}
+                hidden: ${{ inputs.k8s.volumes.pvc != Existing }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
               pvc_storage_size:
                 label: Enter PVC Size
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc !== New }}
+                hidden: ${{ inputs.k8s.volumes.pvc != New }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
                 default: 10Gi
               pvc_storage_class:
                 label: Enter PVC Storage Class
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc !== New }}
+                hidden: ${{ inputs.k8s.volumes.pvc != New }}
                 ignore: ${{ .hidden }}
                 optional: true
                 tooltip: Leave blank to use the default storage class configured in the cluster.
@@ -666,14 +665,14 @@ jobs:
                 label: Persist PVC After Completion
                 type: boolean
                 default: false
-                hidden: ${{ inputs.k8s.volumes.pvc !== 'New' }}
+                hidden: ${{ inputs.k8s.volumes.pvc != 'New' }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
                 tooltip: If true, the PVC will persist after the job is canceled or completed. If false, it will be deleted.
               pvc_name:
                 label: Enter PVC Name
                 type: string
-                hidden: ${{ inputs.k8s.volumes.pvc_persist === false || inputs.k8s.volumes.pvc !== New  }}
+                hidden: ${{ inputs.k8s.volumes.pvc_persist === false || inputs.k8s.volumes.pvc != New  }}
                 ignore: ${{ .hidden }}
                 optional: ${{ .hidden }}
           resources:
@@ -729,7 +728,7 @@ jobs:
                   gpu_resource_key:
                     label: Custom GPU Resource Key
                     type: string
-                    hidden: ${{ inputs.k8s.resources.limits.select_gpu !== Custom }}
+                    hidden: ${{ inputs.k8s.resources.limits.select_gpu != Custom }}
                     ignore: ${{ .hidden }}
                     tooltip: |
                       Specify a custom GPU resource key for Kubernetes, such as:
@@ -751,7 +750,7 @@ jobs:
       service_k8s:
         type: group
         label: Service Settings
-        hidden: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+        hidden: ${{ inputs.targetType != 'kubernetes-cluster' }}
         items:
           image:
             label: Pgadmin4 Image
@@ -760,11 +759,11 @@ jobs:
             tooltip: Sample container from https://hub.docker.com/r/dpage/pgadmin4/
           email:
             label: Email
-            optional: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+            optional: ${{ inputs.targetType != 'kubernetes-cluster' }}
             type: string
             tooltip: Enter email for PGADMIN_DEFAULT_EMAIL variable
           password:
             label: Password
-            optional: ${{ inputs.targetType !== 'kubernetes-cluster' }}
+            optional: ${{ inputs.targetType != 'kubernetes-cluster' }}
             type: password
             tooltip: Enter password for PGADMIN_DEFAULT_PASSWORD variable
