Update general.yaml (#695)

diff --git a/workflow/script_submitter/general.yaml b/workflow/script_submitter/general.yaml
--- a/workflow/script_submitter/general.yaml
+++ b/workflow/script_submitter/general.yaml
@@ -26,7 +26,7 @@ jobs:
           set -x
           if [[ "${{ inputs.use_existing_script }}" == true ]]; then
             if [ ! -f "${{ inputs.script_path }}" ]; then
-                echo "(date) ERROR: File ${{ inputs.script_path }} does not exist or is not a regular file." >&2
+                echo "$(date) ERROR: File ${{ inputs.script_path }} does not exist or is not a regular file." >&2
                 exit 1
             fi
             cp ${{ inputs.script_path }} run-template.sh
